### ISSUE TITLE
count_the_days has a carriage return in it.

### ISSUE THREAD

**Issue by Petro31** [Petro31/easy-time-jinja#23]

**Comment by Petro31** [comment]
2.0.0

**Comment by Elu43** [comment]
Hello @Petro31 

I think easy_relative_time has the same problem :

with easy_time :

![Image](https://github.com/user-attachments/assets/8c8673ec-e9dd-4db9-96e4-ce43b76ac7a1)

with easy_relative_time :

![Image](https://github.com/user-attachments/assets/34597398-97c8-4a1f-be99-cc26888e0526)
