### ISSUE TITLE
FR: add drop in functionality for month() on timestamp entities

### ISSUE THREAD

**Issue by Mariusthvdb** [Petro31/easy-time-jinja#27]
followup from [Discord](https://discord.com/channels/330944238910963714/672223497736421388/1198963164327456818)

have a timestamp entity like

```
{{states('sensor.afvalwijzer_plastic')}}
```

which outputs ' 2024-02-02'

for various dashboards/templates, it would be very nice to be able to do

```
{% set trash = 'sensor.afvalwijzer_plastic' %}
{% from 'easy_time.jinja' import month %}
{{month(trash)}}
```

or 
```
month(states(trash))
```

to output the month name

which would be much nicer than
```
{{month(as_datetime(states(trash)).month)}}
```
which currently does the job alright

please consider adding that?
thx

**Comment by Petro31** [comment]
Added in 2.1.0

**Comment by Mariusthvdb** [comment]
nice!

```
% set trash = 'sensor.afvalwijzer_plastic' %}
{% from 'easy_time.jinja' import month, weekday %}
{{weekday(trash)}}  {{month(trash)}}

{{(states(trash)|as_datetime).day}}
```

<img width="970" alt="Scherm­afbeelding 2024-10-15 om 23 15 59" src="https://github.com/user-attachments/assets/28dfd62e-a1ba-4ae7-8888-fe6e0361eafb">
