### ISSUE TITLE
<Integration Petro31/easy-time-jinja> Repository structure for v2.0.0.3 is not compliant

### ISSUE THREAD

**Issue by Someguitarist** [Petro31/easy-time-jinja#34]
I get <Integration Petro31/easy-time-jinja> Repository structure for v2.0.0.3 is not compliant when trying to add this to HACs.  Am I missing anything?

**Comment by Petro31** [comment]
custom templates aren't integrations, you have to choose `template`.  If you don't see template, you aren't using experimental features.
