### ISSUE TITLE
in french, ago is before the time

### ISSUE THREAD

**Issue by papo-o** [Petro31/easy-time-jinja#4]
hello 
with easy_relative_time the french result isn't correct
ex: "5 days ago" is translate to "5 jours il y a" but the right translation is "Il y a 5 jours"
is there any way to solve this ?

**Comment by Petro31** [comment]
Currently, there is no way to change this.

**Comment by papo-o** [comment]
Shame

**Comment by Petro31** [comment]
@papo-o It'll be fixed in the next version

**Comment by Petro31** [comment]
Fixed in 1.0.7

**Comment by papo-o** [comment]
thanks
