### ISSUE TITLE
Wrong months in Spanish

### ISSUE THREAD

**Issue by rgallo67** [Petro31/easy-time-jinja#42]
Hi,

After august, the month names are displaced one position. E.g. now appears 'noviembre' instead 'octubre' (the right one).

I believe that the problem is that after 'agosto' there isn't a comma:

    'months':[
      'enero',
      'febrero',
      'marzo',
      'abril',
      'mayo',
      'junio',
      'julio',
      'agosto' 
      'septiembre',
      'octubre',
      'noviembre',
      'diciembre'
    ]

Please, solve this little problem... thks.

**Comment by rgallo67** [comment]
Hi,

Yes, the macro I'm using is month. This is the template:

{% from 'easy_time.jinja' import month,weekday %}
{{ weekday('None', 'es')|capitalize + now().strftime(", %d de ") + month('None', 'es') + now().strftime(" de %Y") }}

**Comment by chemelli74** [comment]
> {% from 'easy_time.jinja' import month,weekday %}
> {{ weekday('None', 'es')|capitalize + now().strftime(", %d de ") + month('None', 'es') + now().strftime(" de %Y") }}

I can confirm that using 

```yaml
{% from 'easy_time.jinja' import month,weekday %}
{{ weekday('None', 'es')|capitalize + now().strftime(", %d de ") + month('None', 'it') + now().strftime(" de %Y") }}
```
shows

`Martes, 15 de ottobre de 2024`

so is only related to ES

**Comment by Petro31** [comment]
> Hi,
> 
> Yes, the macro I'm using is month. This is the template:
> 
> {% from 'easy_time.jinja' import month,weekday %} {{ weekday('None', 'es')|capitalize + now().strftime(", %d de ") + month('None', 'es') + now().strftime(" de %Y") }}

Are you sure you're using the latest release?  The current release has the comma, and the month macro works as expected when I set the language to es

**Comment by rgallo67** [comment]
I've downloaded new version (v2.1.0.2) and the problem is solved.

Thank you.
