### ISSUE TITLE
[Feature Request] Short versions of days & months

### ISSUE THREAD

**Issue by bavala3010** [Petro31/easy-time-jinja#45]
Currently,  the weekday and month variables display the full names;
eg. Monday, Tuesday, January, February etc. 

In some cases, it would be useful to be able to use short versions:
eg. Mon, Tue, Jan, Feb etc.

Can this be taken up as an enhancement?

Thanks.

**Comment by Petro31** [comment]
added in https://github.com/Petro31/easy-time-jinja/commit/1533922315bea3fd8d053991ae780045c0fc42a8
