### ISSUE TITLE
custom_time_attr bug

### ISSUE THREAD

**Issue by Pulpyyyy** [Petro31/easy-time-jinja#8]
Hello

Testing macros I found something strange
![image](https://user-images.githubusercontent.com/32004297/234366462-810f8e8c-4e1c-42a4-97fb-2a1bfd3d07eb.png)
With 0 , Day should be in singular instead of plural. 
Even better :
- if day value is >1 and <2, souldn't it return tomorrow ?
- if day value is >0 and <1, returns today ?
- if day value >-1  and <0 returns yesterday ?

**Comment by Pulpyyyy** [comment]
Great  news
So 0 days, 1 day ?
French's grammar is weird, but English's one isn't bad either.

**Comment by Petro31** [comment]
> So 0 days, 1 day ?

Yeah, at least in English this is how it's done.  That's what I modeled it after.  I do not know about other languages, but I would assume it would be the same.

**Comment by Petro31** [comment]
new macro in 1.0.7
